apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-frontend
data:
  default.conf: |
    upstream hello {
        server 32.68.220.18;
    }

    server {
        listen 80;
    
        location / {
                proxy_pass http://32.68.220.18:34100;
        }
    }
