apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: kl111b
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - mtn52r08c001
      containers:
      - name: test-flask
        image: "docker.io/library/docker_flask:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
