apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      nodeSelector:
        node: mtn52r08c001
      containers:
      - name: my-nginx
        image: docker.io/library/nginx-flask:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
